## Lecture 2: Decision Analysis Overview {#decision_analysis}
<!-- reference with [Decision Analysis](#decision_analysis) -->

Welcome to lecture 2 of **Decision Analysis and Forecasting for Agricultural Development**. In this lecture we will follow a [six-part micro-series of videos](https://www.youtube.com/playlist?list=PLe1C9W5AtEiBzmXFf-XzmXH8NNJjqs0IY) and use the Lecture 2 Slack channel and Zoom meeting to follow up. This will allow us all to have a chance to see your progress, provide feedback. It will be encouraging to others to see activity from colleagues. Feel free to bring up any questions or concerns in the Slack or to [Dr. Cory Whitney](mailto:cory.whitney@uni-bonn.de?subject=[Seminar_2]%20Decision%20Analysis%20Lecture) or the course tutor.

Please take a few minutes to watch these six short videos before our meeting. 

### Introduction

The introduction outlines the general theory and application of Decision Analysis tools. At the end of the video please take a moment to think about decisions that are made in agricultural development, ideally decisions that are relevant to your research interests. Please share these with us in the Slack channel.

<iframe width="560" height="315" src="https://www.youtube.com/embed/7P2YI9-smfU" frameborder="0" allowfullscreen></iframe>

```{r letter-a, echo=FALSE}
question("What is the main concern of Decision Analysis for Agricultural Development?",
  answer("How do people make decisions?"),
  answer("What does the data tell us about development?"),
  answer("How will decisions influence future sustainability?", correct = TRUE),
  answer("How can we perform analyses of big data for policy advice?")
)
```

### Part 1: Approaches

Part 1 gives an overview of various approaches in agricultural research and of the Decision Analysis paradigm. At the end of the video please take a moment to think about a situation where Decision Analysis might be applicable. Try and identify a decision maker with a choice between different options and with uncertainty about the outcome.

<iframe width="560" height="315" src="https://www.youtube.com/embed/IRZZokPD3GU" frameborder="0" allowfullscreen></iframe>


### Part 2: Decision Analysis

Part 2 offers some background on the theory and development of Decision Analysis and how we apply it in agricultural decisions. At the end of the video please take some time to think about a practical application of the kinds of approaches to dealing with uncertainty that are used in Decision Analysis. Describe a few variables that you consider difficult to measure but for which the effects on a decision might be possible to describe as uncertainty distributions.

<iframe width="560" height="315" src="https://www.youtube.com/embed/UvLiq85W398" frameborder="0" allowfullscreen></iframe>

### Part 3: Model Building

Part 3 gives an overview of model building processes and approaches. At the end of this video take some time to draw a decision impact pathway. Draw a conceptual diagram of an agricultural development decision. Include the major factors that would influence the decision, no matter how difficult they might be to measure. Feel free to use any program you like to make this drawing. I like to draw digital diagrams with Power point, [Google Slides](https://www.google.com/slides/about/), [Biorender](https://app.biorender.com/biorender-templates). [Loopy](https://ncase.me/loopy/) is also good. For the more advance R users you might like the [igraph library](https://igraph.org/r/). For those who prefer analog, a photo or scan of a hand drawn diagram is also welcome.

<iframe width="560" height="315" src="https://www.youtube.com/embed/fikoVbnoNOQ" frameborder="0" allowfullscreen></iframe>

### Part 4: Overcoming Bias

Part 4 gives an overview of various types of cognitive biases and outlines how these can interfere with the definition of and parameterization of models. The session ends with a number of approaches that can be applied to help in overcoming these biases and outlines the calibration training process whereby experts are trained to give accurate estimates of their own uncertainty. At the end of the video please take some time to consider the variables in your conceptual diagram that might benefit from calibrated estimates. Describe variables in your model that might be difficult to measure but the effects of which might be possible to describe with calibrated-expert derived uncertainty distributions.

<iframe width="560" height="315" src="https://www.youtube.com/embed/dlUz5XT-u98" frameborder="0" allowfullscreen></iframe>

### Parts 5 and 6: Case Studies, Conclusions

Parts 5 and 6 offer some brief Decision Analysis case studies and conclusions. At the end of the video please take some time to revisit your model and consider these approaches in practice. Feel free to discuss in Slack about what application these approaches might have with regard to your research. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/_Yq4E85a7xM" frameborder="0" allowfullscreen></iframe>

### Group discussion reading: 

- Anderson, Jock, John Dillon, and Brian Hardaker. Agricultural Decision Analysis. Ames, Iowa: Iowa State University Press, 1978. *Introduction, pages 1-16*

<!-- ## Further reading -->

<!-- -	Overview of DA (Hubbard, Anderson, Howard) -->
<!-- -	Brief examples (Vietnam…, Uganda, Calluna…) -->
<!-- -	Hubbard (selected chapters from ‘How to Measure Anything’) -->
<!-- -	Howard (selected chapters from ‘Decision Analysis’ and recorded talks) -->

Watch '[Lessons from applying decision science in the public health sector](https://www.youtube.com/watch?v=f1E3Iv8juC0)' by Professor Karl Claxton in the Constructing a Digital Environment Webinar Series.

