## Seminar 7: Calibration training  {#calibration_seminar} 
<!-- reference with [Calibration training](#calibration_seminar) -->

Welcome to the sixth seminar of **Decision Analysis and Forecasting for Agricultural Development**. This week we will be going through the materials that were mentioned in the [Calibrating experts lecture](#calibration_lecture).

Your work for this this seminar is to review materials from Lecture 7 on the methods of calibration and prepare to be subjected to the calibration process.

To prepare please load the required calibration sheets from our shared Slack work space. 

After this session please consider the inputs that will be necessary for your own model and prepare the input table and formulate questions for eliciting calibrated estimates from your colleagues and/or any experts that you have identified for your team's model.

### Further tools

Sign in to [GuidedTrack calibration training](https://www.openphilanthropy.org/calibration) to get your confidence intervals results.

Sign in to the [Prediction Book](https://predictionbook.com/) to *'Find out just how sure you should be, and get better at being only as sure as the facts justify'*.

### Group discussion - food for thought

1. What do you think about the idea of taking estimates as values for the impact models?

2. What do you think about the method of calibration training as presented? Do you have suggestions how to change or improve it?

3. Can you think of further cognitive biases and how to deal with them?
