## Seminar: Using R and RStudio {#r_rstudio} 
<!-- [Using R and RStudio](#r_rstudio) -->

Welcome to **Decision Analysis and Forecasting for Agricultural Development**. Feel free to bring up any questions or concerns in the Slack or to [Dr. Cory Whitney](mailto:cory.whitney@uni-bonn.de?subject=[Seminar_4]%20Decision%20Analysis%20Lecture) or the course tutor.

Remember that this is an experiential course and will be based largely on work from your side that is supported by us, rather than passive learning where we deliver content. In order to work with us in this course you will need to have some basic tools.

The first step in getting ready for the work of this course is to install and run [R](https://www.r-project.org/) [@R-base] and [RStudio](https://rstudio.com/). 

If you already have R and RStudio loaded then you should be able to follow parts our R tutorial. Please follow [Data Wrangling Part one](https://agtools.app/learning_r/#section-data-wrangling-part-1) and [Data Wrangling Part two](https://agtools.app/learning_r/#section-data-wrangling-part-2) portions of the tutorial. Share the results of your work with the 'ggplot2' 'diamonds' data [@R-ggplot2] after you have worked through these materials.

<!-- remake and embed R course materials -->
<!-- world cafe in zoom? a kind of 'speed dating' app... get people to converse-->

### Further Reading 

- Check out the [R Studio Tidyverse style guide](https://style.tidyverse.org/index.html)